"""Historical natural-disaster frequency from National Fire Agency (NFA) statistics.

Data: data/nfa_disaster_events.csv, generated by scripts/convert_nfa_stats.py from the NFA workbook
「臺灣地區天然災害損失統計表」(https://www.nfa.gov.tw/cht/index.php?code=list&ids=233), one row per event
1958-2025 with deaths and households destroyed / half-destroyed. The workbook carries no monetary losses,
so this module only provides frequency and physical severity; money is layered on by the actuarial engine.
"""
from __future__ import annotations

import csv
from functools import lru_cache
from pathlib import Path

DEFAULT_CSV = Path(__file__).resolve().parent / "data" / "nfa_disaster_events.csv"
SOURCE = "內政部消防署 臺灣地區天然災害損失統計表 1958-2025 (https://www.nfa.gov.tw/cht/index.php?code=list&ids=233)"
# English name of the same table, for the bilingual report.
SOURCE_EN = "National Fire Agency, Ministry of the Interior: Natural Disaster Loss Statistics for Taiwan 1958-2025"

# 1995 onwards: the NFA has existed since 1995 and collects the data itself, and post-1990s building codes
# make earlier household-loss counts unrepresentative of today's exposure.
DEFAULT_SINCE_YEAR = 1995
# An event is "severe" when at least this many households were destroyed or half-destroyed.
DEFAULT_SEVERE_THRESHOLD = 50
LOW_SAMPLE_BELOW = 5

_INT_FIELDS = ("year", "month", "day", "deaths", "missing", "injured",
               "households_destroyed", "households_half_destroyed")

# Order matters: a typhoon story usually also mentions the rain and flooding it causes.
_PERIL_KEYWORDS = (
    ("typhoon", ("颱風", "颱", "風災", "typhoon", "hurricane", "cyclone")),
    ("flood", ("豪雨", "淹水", "水災", "水患", "洪水", "山洪", "flood", "flooding")),
    ("earthquake", ("地震", "earthquake", "quake")),
)


@lru_cache(maxsize=4)
def _load(path: str) -> tuple[dict, ...]:
    with open(path, newline="", encoding="utf-8") as fh:
        rows = []
        for row in csv.DictReader(fh):
            for key in _INT_FIELDS:
                row[key] = int(row[key])
            rows.append(row)
    return tuple(rows)


def load_events(path: str | Path = DEFAULT_CSV) -> list[dict]:
    return [dict(r) for r in _load(str(path))]


def classify_peril(text: str) -> str | None:
    lowered = (text or "").lower()
    for peril, keywords in _PERIL_KEYWORDS:
        if any(k in lowered for k in keywords):
            return peril
    return None


def peril_statistics(peril: str, since_year: int = DEFAULT_SINCE_YEAR,
                     severe_threshold: int = DEFAULT_SEVERE_THRESHOLD, events: list[dict] | None = None) -> dict | None:
    """Annual frequency and severity of one peril over [since_year, latest year in the data]."""
    all_events = events if events is not None else load_events()
    if not all_events:
        return None
    until_year = max(e["year"] for e in all_events)
    window = [e for e in all_events if e["peril"] == peril and e["year"] >= since_year]
    if not window:
        return None

    years_observed = until_year - since_year + 1
    households = lambda e: e["households_destroyed"] + e["households_half_destroyed"]
    loss_weighted = lambda e: e["households_destroyed"] + 0.5 * e["households_half_destroyed"]
    severe = [e for e in window if households(e) >= severe_threshold]
    severe_years = {e["year"] for e in severe}
    mean = lambda values: (sum(values) / len(values)) if values else 0.0

    return {
        "peril": peril,
        "source": SOURCE,
        "source_en": SOURCE_EN,
        "since_year": since_year,
        "until_year": until_year,
        "years_observed": years_observed,
        "event_count": len(window),
        "events_per_year": len(window) / years_observed,
        "severe_threshold": severe_threshold,
        "severe_event_count": len(severe),
        "severe_events_per_year": len(severe) / years_observed,
        "annual_probability": len(severe_years) / years_observed,
        "mean_households_per_severe_event": mean([households(e) for e in severe]),
        "mean_loss_weighted_households": mean([loss_weighted(e) for e in severe]),
        "low_sample": len(severe) < LOW_SAMPLE_BELOW,
    }
